# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "install node_module"
          command: npm install
      - save_cache:
          paths: node_module
          key: node_module_cache
      - run:
          name: run lint
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Test"
          command: "echo test step!"
      - restore_cache:
          keys:
            - "node_module_cache"
      - run:
          name: "install node_module"
          command: npm install
      - run:
          name: run test
          command: npm run test
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Analyze"
          command: "echo analyze step"
      - restore_cache:
          keys:
            - "node_module_cache"
      - run:
          name: "install node_module"
          command: npm install
      - run:
          name: run analyze
          command: npm run analyze
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
